select * from customer_shopping_behavior limit 20
--q1: What is the total revenue generated by male vs female customers
select gender, SUM(purchase_amount) as revenue from customer_shopping_behavior group by gender

--q2: Which customers used a discount but still spent more than average purchase amount
Select customer_id,purchase_amount from customer_shopping_behavior
where discount_applied = 'Yes' and purchase_amount >= (Select AVG(purchase_amount)  from customer_shopping_behavior)

--q3: Which are the top 5 products with the highest average review rating
select item_purchased, Avg(review_rating) as "Average Product Rating"
from customer_shopping_behavior
group by item_purchased
order by avg(review_rating) desc
limit 5;

--q4: compare the average purchase amounts between standard and express shipping
select shipping_type,
Round(AVG(purchase_amount),2)
from customer_shopping_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

--q5: DO subscribed customer spend more? Compare average spend and total revenue
-----between subscribers and non-subscribers
select subscription_status,
Count(customer_id) as total_customers,
Round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_shopping_behavior
group by subscription_status
order by total_revenue,avg_spend desc

--q6: which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(CASE when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc
limit 5;

--q7:segment customers into new,returning and loyal based on their total
----number of previous purchases,and show the count of each segment
WITH customer_type AS (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer_shopping_behavior
)

SELECT 
    customer_segment,
    COUNT(*) AS "number of customers"
FROM customer_type
GROUP BY customer_segment;

--q8: what are the top 3 most purchased products within each category?
with item_counts as (
 select category,
 item_purchased,
 count(customer_id) as total_orders,
 ROW_NUMBER() over (partition by category order by count (customer_id) desc) as item_rank
 from customer_shopping_behavior
 group by category, item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--q9: are customers who are repeat buyer(more than 5 previous purchases) alse likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status;

--q10:what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping_behavior
group by age_group
order by total_revenue desc;
 



















